# --- Removed parameters --- #
# all of the parameter types from the website with their IDs.
# mathops and comparison ops are handdled by the intepreter.
#
import enum
class compareOp(enum):
    pass
class mathOp(enum):
    pass
class typeOp(enum):
    pass
class ActionId(enum):
    _1 = -1
    actionid_attack = 600
    actionid_defend = 601
    actionid_build = 602
    actionid_heal = 603
    actionid_convert = 604
    actionid_explore = 605
    actionid_stop = 606
    actionid_runaway = 607
    actionid_retreat = 608
    actionid_gather = 609
    actionid_move = 610
    actionid_patrol = 611
    actionid_follow = 612
    actionid_hunt = 613
    actionid_transport = 614
    actionid_trade = 615
    actionid_evade = 616
    actionid_enter = 617
    actionid_repair = 618
    actionid_train = 619
    actionid_research = 620
    actionid_unload = 621
    actionid_relic = 631
class Age(enum):
    dark_age = 0
    feudal_age = 1
    castle_age = 2
    imperial_age = 3
    post_imperial_age = 105
class AttackStance(enum):
    _1 = -1
    stance_aggressive = 0
    stance_defensive = 1
    stance_stand_ground = 2
    stance_no_attack = 3
class AttrId(enum):
    attribute_hp = 0
    attribute_los = 1
    attribute_obj_max = 2
    attribute_radius_x = 3
    attribute_radius_y = 4
    attribute_speed = 5
    attribute_turn_speed = 6
    attribute_armor = 8
    attribute_weapon = 9
    attribute_speed_of_attack = 10
    attribute_hit_chance = 11
    attribute_weapon_range = 12
    attribute_work_rate = 13
    attribute_carry_capacity = 14
    attribute_base_armor = 15
    attribute_missile_id = 16
    attribute_building_facet = 17
    attribute_defensive_terrain = 18
    attribute_targetting_type = 19
    attribute_minimum_weapon_range = 20
    attribute_attribute_amount_held = 21
    attribute_area_effect = 22
    attribute_search_radius = 23
    attribute_hidden_damage_resist = 24
    attribute_icon_id = 25
    attribute_fire_missile_at_frame = 41
    attribute_area_effect_level = 44
    attribute_blast_defense_level = 45
    attribute_shown_attack = 46
    attribute_shown_range = 47
    attribute_shown_melee_armor = 48
    attribute_name_id = 50
    attribute_description_id = 51
    attribute_terrain_restriction = 53
    attribute_death_spawn_obj = 57
    attribute_hotkey_id = 58
    attribute_resource_cost = 100
    attribute_creation_time = 101
    attribute_garrison_arrows = 102
    attribute_food_cost = 103
    attribute_wood_cost = 104
    attribute_gold_cost = 105
    attribute_stone_cost = 106
    attribute_max_dup_missiles = 107
    attribute_garrison_heal_rate = 108
    attribute_regenration_rate = 109
class BuildingId(enum):
    watch_tower_line = -398
class Civ(enum):
    gaia = 0
    briton = 1
    frankish = 2
    gothic = 3
    teutonic = 4
    japanese = 5
    chinese = 6
    byzantine = 7
    persian = 8
    saracen = 9
    turkish = 10
    viking = 11
    mongol = 12
    celtic = 13
    spanish = 14
    aztec = 15
    mayan = 16
    hun = 17
    korean = 18
    italian = 19
    indian = 20
    incan = 21
    magyar = 22
    slavic = 23
    portuguese = 24
    ethiopian = 25
    malian = 26
    berbers = 27
    khmer = 28
    malay = 29
    burmese = 30
    vietnamese = 31
    bulgarians = 32
    tatars = 33
    cumans = 34
    lithuanians = 35
    burgundians = 36
    sicilians = 37
    poles = 38
    bohemians = 39
    dravidians = 40
    bengalis = 41
    gurjaras = 42
    romans = 43
    armenians = 44
    georgians = 45
    achaemenids = 46
    athenians = 47
    spartans = 48
class ClassId(enum):
    all_units_class = -1
    archery_class = 900
    monument_class = 901
    trade_cog_class = 902
    building_class = 903
    villager_class = 904
    ocean_fish_class = 905
    infantry_class = 906
    forage_class = 907
    stone_mine_class = 908
    prey_animal_class = 909
    predator_animal_class = 910
    miscellaneous_class = 911
    cavalry_class = 912
    siege_weapon_class = 913
    terrain_class = 914
    tree_class = 915
    monastery_class = 918
    trade_cart_class = 919
    transport_ship_class = 920
    fishing_ship_class = 921
    warship_class = 922
    cavalry_cannon_class = 923
    wall_class = 927
    flag_class = 930
    gold_mine_class = 932
    shore_fish_class = 933
    petard_class = 935
    cavalry_archer_class = 936
    gate_class = 939
    relic_class = 942
    monk_with_relic_class = 943
    archery_cannon_class = 944
    scout_cavalry_class = 947
    farm_class = 949
    packed_trebuchet_class = 951
    tower_class = 952
    unpacked_trebuchet_class = 954
    scorpion_class = 955
    livestock_class = 958
    king_class = 959
class CmdId(enum):
    cmdid_flag = 0
    cmdid_livestock_gaia = 1
    cmdid_civilian_building = 2
    cmdid_villager = 3
    cmdid_military = 4
    cmdid_trade = 5
    cmdid_monk = 6
    cmdid_transport = 7
    cmdid_relic = 8
    cmdid_fishing_ship = 9
    cmdid_military_building = 10
class ColorId(enum):
    pass #empty options_dict
class Commodity(enum):
    food = 0
    wood = 1
    stone = 2
class Defconst(enum):
    pass #empty options_dict
class Difficulty(enum):
    extreme = -1
    hardest = 0
    hard = 1
    moderate = 2
    easy = 3
    easiest = 4
class DiffParameterId(enum):
    ability_to_maintain_distance = 0
    ability_to_dodge_missiles = 1
class DUCAction(enum):
    action_default = 0
    action_move = 1
    action_patrol = 2
    action_guard = 3
    action_follow = 4
    action_stop = 5
    action_ground = 6
    action_garrison = 7
    action_delete = 8
    action_unload = 9
    action_train = 10
    action_gather = 11
    action_lock = 12
    action_work = 13
    action_ungarrison = 14
    action_drop_relic = 15
    action_pack = 16
    action_unpack = 17
    action_none = 18
    action_attack_move = 19
    action_transform = 20
class EffectId(enum):
    effect_set_attribute = 0
    effect_mod_resource = 1
    effect_enable_object = 2
    effect_upgrade_unit = 3
    effect_add_attribute = 4
    effect_mul_attribute = 5
    effect_mul_resource = 6
    effect_enable_tech = 7
    effect_modify_tech = 8
    effect_set_player_data = 9
class EscrowGoalId(enum):
    pass #empty options_dict
class EventId(enum):
    pass #empty options_dict
class EventType(enum):
    trigger = 0
class ExploredState(enum):
    explored_no = 0
    explored_active = 15
    explored_yes = 128
class FactId(enum):
    game_time = 0
    population_cap = 1
    population_headroom = 2
    housing_headroom = 3
    idle_farm_count = 4
    food_amount = 5
    wood_amount = 6
    stone_amount = 7
    gold_amount = 8
    escrow_amount = 9
    commodity_buying_price = 10
    commodity_selling_price = 11
    dropsite_min_distance = 12
    soldier_count = 13
    attack_soldier_count = 14
    defend_soldier_count = 15
    warboat_count = 16
    attack_warboat_count = 17
    defend_warboat_count = 18
    current_age = 19
    current_score = 20
    civilization = 21
    player_number = 22
    player_in_game = 23
    unit_count = 24
    unit_type_count = 25
    unit_type_count_total = 26
    building_count = 27
    building_type_count = 28
    building_type_count_total = 29
    population = 30
    military_population = 31
    civilian_population = 32
    random_number = 33
    resource_amount = 34
    player_distance = 35
    allied_goal = 36
    allied_sn = 37
    resource_percent = 38
    enemy_buildings_in_town = 39
    enemy_units_in_town = 40
    enemy_villagers_in_town = 41
    players_in_game = 42
    defender_count = 43
    building_type_in_town = 44
    unit_type_in_town = 45
    villager_type_in_town = 46
    gaia_type_count = 47
    gaia_type_count_total = 48
    cc_gaia_type_count = 49
    current_age_time = 50
    timer_status = 51
    players_tribute = 52
    players_tribute_memory = 53
    treaty_time = 54
class FactParameter(enum):
    pass #empty options_dict
class FindPlayerMethod(enum):
    find_attacker = 0
    find_random = 1
    find_closest = 2
    find_ordered = 3
class Flag(enum):
    pass #empty options_dict
class Formation(enum):
    _1 = -1
    formation_line = 2
    formation_box = 4
    formation_stagger = 7
    formation_flank = 8
class GameType(enum):
    random_map = 0
    regicide = 1
    death_match = 2
    scenario = 3
    king_of_the_hill = 5
    wonder_race = 6
    defend_the_wonder = 7
    turbo_random_map = 8
    capture_the_relic = 10
    sudden_death = 11
    battle_royale = 12
    empire_wars = 13
class GoalId(enum):
    pass #empty options_dict
class GroupId(enum):
    pass #empty options_dict
class GroupType(enum):
    group_type_land_attack = 100
    group_type_land_explore = 101
    group_type_water_attack = 102
    group_type_water_explore = 103
    group_type_transport_ship = 104
    group_type_fishing_ship = 105
    group_type_water_trade = 106
    group_type_forward_builder = 107
    group_type_monk = 108
    group_type_land_trade = 109
class GuardFlag(enum):
    guard_flag_victory = 1
    guard_flag_resource = 2
    guard_flag_inverse = 4
class Id(enum):
    pass #empty options_dict
class IdleType(enum):
    idle_type_villager = 0
    idle_type_trade_cart = 1
    idle_type_fishing_ship = 2
    idle_type_trade_cog = 3
class Index(enum):
    pass #empty options_dict
class ItemId(enum):
    pass #empty options_dict
class LanguageId(enum):
    pass #empty options_dict
class LineId(enum):
    stone_wall_line = -399
    watch_tower_line = -398
    archer_line = -299
    cavalry_archer_line = -298
    skirmisher_line = -297
    militiaman_line = -296
    spearman_line = -295
    demolition_ship_line = -294
    fire_ship_line = -293
    galley_line = -292
    battering_ram_line = -291
    mangonel_line = -290
    scorpion_line = -289
    camel_line = -288
    knight_line = -287
    scout_cavalry_line = -286
    cannon_galleon_line = -284
    longboat_line = -283
    turtle_ship_line = -282
    berserk_line = -281
    cataphract_line = -280
    chu_ko_nu_line = -279
    huskarl_line = -278
    janissary_line = -277
    longbowman_line = -276
    mameluke_line = -275
    mangudai_line = -274
    samurai_line = -273
    teutonic_knight_line = -272
    throwing_axeman_line = -271
    war_elephant_line = -270
    war_wagon_line = -269
    woad_raider_line = -268
    jaguar_man_line = -267
    eagle_warrior_line = -266
    plumed_archer_line = -265
    tarkan_line = -264
    conquistador_line = -263
    camel_archer_line = -285
    genoese_crossbowman_line = -262
    elephant_archer_line = -261
    boyar_line = -260
    magyar_huszar_line = -259
    kamayuk_line = -258
    caravel_line = -257
    organ_gun_line = -256
    gbeto_line = -255
    shotel_warrior_line = -254
    genitour_line = -253
    ballista_elephant_line = -252
    rattan_archer_line = -251
    arambai_line = -250
    battle_elephant_line = -249
    karambit_warrior_line = -248
    konnik_line = -247
    krepost_konnik_line = -246
    foot_konnik_line = -245
    leitis_line = -244
    kipchak_line = -243
    keshik_line = -242
    steppe_lancer_line = -241
    coustillier_line = -240
    serjeant_line = -239
    donjon_serjeant_line = -238
    obuch_line = -237
    hussite_wagon_line = -236
    bombard_cannon_line = -235
    urumi_swordsman_line = -234
    ratha_melee_line = -233
    chakram_thrower_line = -232
    armored_elephant_line = -231
    ghulam_line = -230
    shrivamsha_rider_line = -229
    ratha_ranged_line = -228
    donjon_spearman_line = -227
    centurion_line = -226
    composite_bowman_line = -225
    monaspa_line = -224
    qizilbash_warrior_line = -223
    immortal_line = -222
    strategos_line = -221
    hippeus_line = -220
    hoplite_line = -219
    war_chariot_line = -218
    lembos_line = -217
    monoreme_line = -216
    ancient_galley_line = -215
    incendiary_ship_line = -214
    catapult_ship_line = -213
class LocalIndex(enum):
    pass #empty options_dict
class LocalList(enum):
    pass #empty options_dict
class MapSize(enum):
    miniature_map = 80
    tiny_map,_tiny = 120
    small_map,_small = 144
    medium_map,_medium = 168
    normal_map,_normal = 200
    large_map,_large = 220
    huge_map,_giant = 240
    giant_map = 252
    massive_map = 276
    enormous_map = 300
    colossal_map = 320
    incredible_map = 360
    monstrous_map = 400
    ludicrous_map,_ludicrous,_ludikris = 480
class MapType(enum):
    scenario_map = -1
    arabia = 9
    archipelago = 10
    baltic = 11
    black_forest = 12
    coastal = 13
    continental = 14
    crater_lake = 15
    fortress = 16
    gold_rush = 17
    highland = 18
    islands = 19
    mediterranean = 20
    migration = 21
    rivers = 22
    team_islands = 23
    scandanavia = 25
    mongolia = 26
    yucatan = 27
    salt_marsh = 28
    arena = 29
    king_of_the_hill = 30
    oasis = 31
    ghost_lake = 32
    nomad = 33
    real_world_spain = 34
    real_world_england = 35
    real_world_midEast = 36
    real_world_texas = 37
    real_world_italy = 38
    real_world_caribbean = 39
    real_world_france = 40
    real_world_jutland = 41
    real_world_nippon = 42
    real_world_byzantium = 43
    custom_map = 44
    acropolis = 67
    budapest = 68
    cenotes = 69
    cityoflakes = 70
    goldenpit = 71
    hideout = 72
    hillfort = 73
    lombardia = 74
    steppe = 75
    valley = 76
    megarandom = 77
    hamburger = 78
    ctr_random = 79
    ctr_monsoon = 80
    ctr_pyramid_descent = 81
    ctr_spiral = 82
    kilimanjaro = 83
    mountain_pass = 84
    nile_delta = 85
    serengeti = 86
    socotra = 87
    real_world_amazon = 88
    real_world_china = 89
    real_world_india = 91
    real_world_madagascar = 92
    real_world_west_africa = 93
    real_world_bohemia = 94
    real_world_earth = 95
    special_map_canyons = 96
    special_map_archipelago = 97
    special_map_enemy_islands = 98
    special_map_far_out = 99
    special_map_front_line = 100
    special_map_inner_circle = 101
    special_map_motherland = 102
    special_map_open_plains = 103
    special_map_ring_of_water = 104
    special_map_snake_pit = 105
    special_map_the_eye = 106
    bog_islands = 112
    mangrove_jungle = 113
    pacific_islands = 114
    sandbank = 115
    water_nomad = 116
    special_map_jungle_islands = 117
    special_map_holy_line = 118
    special_map_border_stones = 119
    special_map_yin_yang = 120
    special_map_jungle_lanes = 121
    golden_swamp = 139
    four_lakes = 140
    land_nomad = 141
    battle_on_the_ice = 142
    el_dorado = 143
    fall_of_axum = 144
    fall_of_rome = 145
    the_majapahit_empire = 146
    amazon_tunnel = 147
    coastal_forest = 148
    african_clearing = 149
    atacama = 150
    seize_the_mountain = 151
    crater = 152
    crossroads = 153
    volcanic_island = 156
    acclivity = 157
    eruption = 158
    frigid_lake = 159
    greenland = 160
    lowland = 161
    marketplace = 162
    meadow = 163
    mountain_range = 164
    northern_isles = 165
    ring_fortress = 166
    runestones = 167
    aftermath = 168
    enclosed = 169
    haboob = 170
    kawasan = 171
    land_madness = 172
    sacred_springs = 173
class MaxDistance(enum):
    pass #empty options_dict
class MaxGarrison(enum):
    pass #empty options_dict
class MinDistance(enum):
    pass #empty options_dict
class MinGarrison(enum):
    pass #empty options_dict
class ObjectData(enum):
    object_data_index = -1
    object_data_id = 0
    object_data_type = 1
    object_data_class = 2
    object_data_category = 3
    object_data_cmdid = 4
    object_data_action = 5
    object_data_order = 6
    object_data_target = 7
    object_data_point_x = 8
    object_data_point_y = 9
    object_data_hitpoints = 10
    object_data_maxhp = 11
    object_data_range = 12
    object_data_speed = 13
    object_data_dropsite = 14
    object_data_resource = 15
    object_data_carry = 16
    object_data_garrisoned = 17
    object_data_garrison_count = 18
    object_data_status = 19
    object_data_player = 20
    object_data_attack_stance = 21
    object_data_action_time = 22
    object_data_target_id = 23
    object_data_formation_id = 24
    object_data_patrolling = 25
    object_data_strike_armor = 26
    object_data_pierce_armor = 27
    object_data_base_attack = 28
    object_data_locked = 29
    object_data_garrison_id = 30
    object_data_train_count = 31
    object_data_tasks_count = 32
    object_data_attacker_count = 33
    object_data_attacker_id = 34
    object_data_under_attack = 35
    object_data_attack_timer = 36
    object_data_point_z = 37
    object_data_precise_x = 38
    object_data_precise_y = 39
    object_data_precise_z = 40
    object_data_researching = 41
    object_data_tile_position = 42
    object_data_tile_inverse = 43
    object_data_distance = 44
    object_data_precise_distance = 45
    object_data_full_distance = 46
    object_data_map_zone_id = 47
    object_data_on_mainland = 48
    object_data_idling = 49
    object_data_move_x = 50
    object_data_move_y = 51
    object_data_precise_move_x = 52
    object_data_precise_move_y = 53
    object_data_reload_time = 54
    object_data_next_attack = 55
    object_data_train_site = 56
    object_data_train_time = 57
    object_data_blast_radius = 58
    object_data_blast_level = 59
    object_data_progress_type = 60
    object_data_progress_value = 61
    object_data_min_range = 62
    object_data_target_time = 63
    object_data_heresy = 64
    object_data_faith = 65
    object_data_redemption = 66
    object_data_atonement = 67
    object_data_theocracy = 68
    object_data_spies = 69
    object_data_ballistics = 70
    object_data_gather_type = 71
    object_data_language_id = 72
    object_data_group_flag = 73
    object_data_hero_flags = 74
    object_data_hero = 75
    object_data_auto_heal = 76
    object_data_no_convert = 77
    object_data_frame_delay = 78
    object_data_attack_count = 79
    object_data_to_precise = 80
    object_data_base_type = 81
    object_data_upgrade_type = 82
    object_data_ownership = 83
    object_data_capture_flag = 84
    object_data_charge_attack_type = 85
    object_data_charge_attack_max = 86
    object_data_charge_attack_amount = 87
    object_data_charge_attack_regeneration_rate = 88
    object_data_charge_attack_event_type = 89
class ObjectId(enum):
    pass #empty options_dict
class ObjectList(enum):
    list_active = 0
    list_inactive = 1
class ObjectStatus(enum):
    status_pending = 0
    status_ready = 2
    status_resource = 3
    status_down = 4
    status_gather = 5
class OnMainland(enum):
    pass #empty options_dict
class Option(enum):
    pass #empty options_dict
class OptionGoalId(enum):
    pass #empty options_dict
class OrderId(enum):
    _1 = -1
    orderid_attack = 700
    orderid_defend = 701
    orderid_build = 702
    orderid_heal = 703
    orderid_convert = 704
    orderid_explore = 705
    orderid_stop = 706
    orderid_runaway = 707
    orderid_retreat = 708
    orderid_gather = 709
    orderid_move = 710
    orderid_patrol = 711
    orderid_follow = 712
    orderid_hunt = 713
    orderid_transport = 714
    orderid_trade = 715
    orderid_evade = 716
    orderid_enter = 717
    orderid_repair = 718
    orderid_train = 719
    orderid_research = 720
    orderid_unload = 721
    orderid_relic = 731
class OutputGoalId(enum):
    pass #empty options_dict
class Percent(enum):
    pass #empty options_dict
class Perimeter(enum):
    pass #empty options_dict
class PlacementType(enum):
    place_normal = 0
    place_forward = 1
    place_control = 2
    place_point = 3
class PlayerNumber(enum):
    this_any_ally = 101
    this_any_computer = 102
    this_any_computer_ally = 103
    this_any_computer_enemy = 104
    this_any_computer_neutral = 105
    this_any_enemy = 106
    this_any_human = 107
    this_any_human_ally = 108
    this_any_human_enemy = 109
    this_any_human_neutral = 110
    this_any_neutral = 111
    my_player_number = "my-player-number"
class PlayerStance(enum):
    ally = 0
    neutral = 1
    any = 2
    enemy = 3
class Point(enum):
    pass #empty options_dict
class PositionType(enum):
    position_center = 0
    position_opposite = 1
    position_corner = 2
    position_enemy = 3
    position_border = 4
    position_mirror = 5
    position_flank = 6
    position_zero = 7
    position_map_size = 8
    position_self = 9
    position_target = 10
    position_focus = 11
    position_object = 12
    position_point = 13
class ProgressType(enum):
    progress_type_train = 102
    progress_type_research = 103
class ProjectileType(enum):
    projectile_town_center = 0
    projectile_castle = 1
    projectile_watch_tower = 2
    projectile_bombard_tower = 3
    projectile_ship = 4
    projectile_siege = 5
    projectile_fortification = 6
    projectile_any = 7
class PriorityType(enum):
    priority_offense = 0
    priority_defense = 1
class RemoteIndex(enum):
    pass #empty options_dict
class RemoteList(enum):
    pass #empty options_dict
class ResearchState(enum):
    research_disabled = -1
    research_unavailable = 0
    research_available = 1
    research_pending = 2
    research_complete = 3
    research_queued = 4
class Resource(enum):
    food = 0
    wood = 1
    stone = 2
    gold = 3
    hunting = 4
    boar_hunting = 5
    deer_hunting = 6
    live_boar = 7
class ResourceType(enum):
    amount_food = 0
    amount_wood = 1
    amount_stone = 2
    amount_gold = 3
    amount_population_cap = 4
    amount_religion = 5
    amount_current_age = 6
    amount_relics = 7
    amount_trade_bonus = 8
    amount_trade_goods = 9
    amount_trade_production = 10
    amount_population = 11
    amount_decay = 12
    amount_discovery = 13
    amount_ruins = 14
    amount_meat = 15
    amount_berries = 16
    amount_fish = 17
    amount_kills = 20
    amount_research_count = 21
    amount_exploration = 22
    amount_convert_priest = 27
    amount_convert_building = 28
    amount_building_limit = 30
    amount_food_limit = 31
    amount_unit_limit = 32
    amount_maintenance = 33
    amount_faith = 34
    amount_faith_recharge_rate = 35
    amount_farm_food = 36
    amount_civilian_population = 37
    amount_all_techs_achieved = 39
    amount_military_population = 40
    amount_conversions = 41
    amount_wonder = 42
    amount_razings = 43
    amount_kill_ratio = 44
    amount_player_killed = 45
    amount_tribute_inefficiency = 46
    amount_gold_bonus = 47
    amount_town_center_unavailable = 48
    amount_gold_counter = 49
    amount_writing = 50
    amount_monasteries = 52
    amount_tribute = 53
    amount_hold_ruins = 54
    amount_hold_relics = 55
    amount_ore = 56
    amount_captured_unit = 57
    amount_trade_good_quality = 59
    amount_trade_market_level = 60
    amount_formations = 61
    amount_building_housing_rate = 62
    amount_gather_tax_rate = 63
    amount_gather_accumulator = 64
    amount_salvage_decay_rate = 65
    amount_allow_formations = 66
    amount_can_convert = 67
    amount_convert_resistance = 77
    amount_trade_vig_rate = 78
    amount_stone_bonus = 79
    amount_queued_count = 80
    amount_training_count = 81
    amount_raider = 82
    amount_boarding_recharge_rate = 83
    amount_starting_villagers = 84
    amount_research_cost_mod = 85
    amount_research_time_mod = 86
    amount_convert_boats = 87
    amount_fish_trap_food = 88
    amount_heal_rate_modifier = 89
    amount_heal_range = 90
    amount_starting_food = 91
    amount_starting_wood = 92
    amount_starting_stone = 93
    amount_starting_gold = 94
    amount_raider_ability = 95
    amount_berserker_heal_timer = 96
    amount_dominant_sheep_control = 97
    amount_object_cost_summation = 98
    amount_research_summation = 99
    amount_relic_income_summation = 100
    amount_trade_income_summation = 101
    amount_castle = 134
    amount_value_killed_by_others = 152
    amount_value_razed_by_others = 153
    amount_killed_by_others = 154
    amount_razed_by_others = 155
    amount_value_current_units = 164
    amount_value_current_buildings = 165
    amount_food_total = 166
    amount_wood_total = 167
    amount_stone_total = 168
    amount_gold_total = 169
    amount_total_value_of_kills = 170
    amount_total_tribute_received = 171
    amount_total_value_of_razings = 172
    amount_total_castles_built = 173
    amount_total_wonders_built = 174
    amount_tribute_score = 175
    amount_convert_min_adj = 176
    amount_convert_max_adj = 177
    amount_convert_resist_min_adj = 178
    amount_convert_resist_max_adj = 179
    amount_convert_building_min = 180
    amount_convert_building_max = 181
    amount_convert_building_chance = 182
    amount_spies = 183
    amount_value_wonders_castles = 184
    amount_food_score = 185
    amount_wood_score = 186
    amount_stone_score = 187
    amount_gold_score = 188
    amount_wood_bonus = 189
    amount_food_bonus = 190
    amount_relic_rate = 191
    amount_heresy = 192
    amount_theocracy = 193
    amount_crenellations = 194
    amount_construction_rate_mod = 195
    amount_hun_wonder_bonus = 196
    amount_spies_discount = 197
    amount_feitoria_food_productivity = 205
    amount_feitoria_wood_productivity = 206
    amount_feitoria_stone_productivity = 207
    amount_feitoria_gold_productivity = 208
    amount_temporary_map_reveal = 209
    amount_reveal_initial_type = 210
    amount_elevation_bonus_higher = 211
    amount_elevation_bonus_lower = 212
    amount_raiding_productivity = 213
    amount_mercenary_kipchak_count = 214
    amount_mercenary_kipchak_limit = 215
    amount_shepherd_productivity = 216
    amount_shared_line_of_sight = 217
    amount_feudal_town_center_limit = 218
    amount_fishing_productivity = 219
    amount_unused_0 = 220
    amount_monument_food_trickle = 221
    amount_monument_wood_trickle = 222
    amount_monument_stone_trickle = 223
    amount_monument_gold_trickle = 224
    amount_relic_food_rate = 225
    amount_villagers_killed_by_gaia = 226
    amount_villagers_killed_by_animal = 227
    amount_villagers_killed_by_ai_player = 228
    amount_villagers_killed_by_human_player = 229
    amount_food_generation = 230
    amount_wood_generation = 231
    amount_stone_generation = 232
    amount_gold_generation = 233
    amount_spawn_cap = 234
    amount_flemish_militia_pop = 235
    amount_gold_farming_productivity = 236
    amount_folwark_collection_amount = 237
    amount_folwark_collection_type = 238
    amount_building_id = 239
    amount_units_converted = 240
    amount_stone_gold_mining_productivity = 241
    amount_workshop_food_trickle = 242
    amount_workshop_wood_trickle = 243
    amount_workshop_stone_trickle = 244
    amount_workshop_gold_trickle = 245
    amount_units_value_total = 246
    amount_buildings_value_total = 247
    amount_villagers_created_total = 248
    amount_villagers_idle_periods_total = 249
    amount_villagers_idle_seconds_total = 250
    amount_trade_food_percent = 251
    amount_trade_wood_percent = 252
    amount_trade_stone_percent = 253
    amount_livestock_food_productivity = 254
    amount_speed_up_building_type = 255
    amount_speed_up_building_range = 256
    amount_speed_up_percentage = 257
    amount_speed_up_object_type = 258
    amount_speed_up_effect_type = 259
    amount_speed_up_secondary_effect_type = 260
    amount_speed_up_secondary_percentage = 261
    amount_civ_name_override = 262
    amount_starting_scout_id = 263
    amount_relic_wood_rate = 264
    amount_relic_stone_rate = 265
    amount_chopping_gold_productivity = 266
    amount_foraging_wood_productivity = 267
    amount_hunting_productivity = 268
    amount_technology_reward_effect = 269
    amount_unit_repair_cost = 270
    amount_building_repair_cost = 271
    amount_elevation_damage_higher = 272
    amount_elevation_damage_lower = 273
    amount_infantry_kill_reward = 274
    amount_military_can_convert = 279
    amount_military_conversion_range_adj = 280
    amount_military_conversion_chance = 281
    amount_military_conversion_recharge_rate = 282
    amount_spawn_stay_inside = 283
    amount_cavalry_kill_reward = 284
    amount_trigger_shared_visibility = 285
    amount_trigger_shared_exploration = 286
    amount_gaia_kills = 300
    amount_player1_kills = 301
    amount_player2_kills = 302
    amount_player3_kills = 303
    amount_player4_kills = 304
    amount_player5_kills = 305
    amount_player6_kills = 306
    amount_player7_kills = 307
    amount_player8_kills = 308
    amount_kills_by_gaia = 325
    amount_kills_by_player1 = 326
    amount_kills_by_player2 = 327
    amount_kills_by_player3 = 328
    amount_kills_by_player4 = 329
    amount_kills_by_player5 = 330
    amount_kills_by_player6 = 331
    amount_kills_by_player7 = 332
    amount_kills_by_player8 = 333
    amount_gaia_razings = 350
    amount_player1_razings = 351
    amount_player2_razings = 352
    amount_player3_razings = 353
    amount_player4_razings = 354
    amount_player5_razings = 355
    amount_player6_razings = 356
    amount_player7_razings = 357
    amount_player8_razings = 358
    amount_razings_by_gaia = 375
    amount_razings_by_player1 = 376
    amount_razings_by_player2 = 377
    amount_razings_by_player3 = 378
    amount_razings_by_player4 = 379
    amount_razings_by_player5 = 380
    amount_razings_by_player6 = 381
    amount_razings_by_player7 = 382
    amount_razings_by_player8 = 383
    amount_gaia_kill_value = 400
    amount_player1_kill_value = 401
    amount_player2_kill_value = 402
    amount_player3_kill_value = 403
    amount_player4_kill_value = 404
    amount_player5_kill_value = 405
    amount_player6_kill_value = 406
    amount_player7_kill_value = 407
    amount_player8_kill_value = 408
    amount_gaia_razing_value = 425
    amount_player1_razing_value = 426
    amount_player2_razing_value = 427
    amount_player3_razing_value = 428
    amount_player4_razing_value = 429
    amount_player5_razing_value = 430
    amount_player6_razing_value = 431
    amount_player7_razing_value = 432
    amount_player8_razing_value = 433
    amount_gaia_tribute = 450
    amount_player1_tribute = 451
    amount_player2_tribute = 452
    amount_player3_tribute = 453
    amount_player4_tribute = 454
    amount_player5_tribute = 455
    amount_player6_tribute = 456
    amount_player7_tribute = 457
    amount_player8_tribute = 458
    amount_tribute_from_gaia = 475
    amount_tribute_from_player1 = 476
    amount_tribute_from_player2 = 477
    amount_tribute_from_player3 = 478
    amount_tribute_from_player4 = 479
    amount_tribute_from_player5 = 480
    amount_tribute_from_player6 = 481
    amount_tribute_from_player7 = 482
    amount_tribute_from_player8 = 483
class RuleDelta(enum):
    pass #empty options_dict
class RuleId(enum):
    pass #empty options_dict
class ScoutMethod(enum):
    scout_center = 0
    scout_opposite = 1
    scout_corner = 2
    scout_enemy = 3
    scout_border = 4
    scout_mirror = 5
    scout_flank = 6
class SearchOrder(enum):
    search_order_none = 0
    search_order_asc = 1
    search_order_desc = 2
class SearchSource(enum):
    search_local = 1
    search_remote = 2
class SetId(enum):
    monk_set = 970
    trebuchet_set = 971
    huskarl_set = 972
    villager_shepherd = 973
    villager_forager = 974
    villager_farmer = 975
    villager_hunter = 976
    villager_fisherman = 977
    villager_food = 978
    villager_wood = 979
    villager_stone = 980
    villager_gold = 981
    villager_builder = 982
    villager_repairer = 983
    villager_base = 984
    tarkan_set = 985
    konnik_set = 986
    kipchak_set = 987
    serjeant_set = 988
    flemish_militia_set = 989
    ratha_set = 990
class SharedGoalId(enum):
    pass #empty options_dict
class SignalId(enum):
    pass #empty options_dict
class SnId(enum):
    pass #empty options_dict
class StartingResources(enum):
    low_resources = 1
    medium_resources = 2
    high_resources = 3
    ultra_high_resources = 4
    infinite_resources = 5
    random_resources = 6
class String(enum):
    pass #empty options_dict
class SubGameType(enum):
    sub_game_type_empire_wars = 1
    sub_game_type_sudden_death = 1
    sub_game_type_regicide = 1
    sub_game_type_king_of_the_hill = 1
class TauntId(enum):
    pass #empty options_dict
class TechId(enum):
    pass #empty options_dict
class Terrain(enum):
    terrain_grass = 0
    terrain_water = 1
    terrain_water_beach = 2
    terrain_dirt3 = 3
    terrain_shallows = 4
    terrain_leaves = 5
    terrain_dirt = 6
    terrain_farm = 7
    terrain_farm_dead = 8
    terrain_grass3 = 9
    terrain_forest = 10
    terrain_dirt2 = 11
    terrain_grass2 = 12
    terrain_forest_palm = 13
    terrain_desert = 14
    terrain_water_old = 15
    terrain_grass_old = 16
    terrain_forest_jungle = 17
    terrain_forest_bamboo = 18
    terrain_forest_pine = 19
    terrain_forest_oak = 20
    terrain_forest_snow = 21
    terrain_water_deep = 22
    terrain_water_medium = 23
    terrain_road = 24
    terrain_road_broken = 25
    terrain_ice = 26
    terrain_foundation = 27
    terrain_water_bridge = 28
    terrain_farm1 = 29
    terrain_farm2 = 30
    terrain_farm3 = 31
    terrain_snow = 32
    terrain_dirt_snow = 33
    terrain_grass_snow = 34
    terrain_ice2 = 35
    terrain_foundation_snow = 36
    terrain_ice_beach = 37
    terrain_road_snow = 38
    terrain_road_fungus = 39
    terrain_koh = 40
    terrain_unknown = 41
class ThreatPlayer(enum):
    pass #empty options_dict
class ThreatSource(enum):
    pass #empty options_dict
class ThreatTarget(enum):
    pass #empty options_dict
class ThreatTime(enum):
    pass #empty options_dict
class TimerId(enum):
    pass #empty options_dict
class TimerState(enum):
    timer_disabled = 0
    timer_triggered = 1
    timer_running = 2
class TypeId(enum):
    pass #empty options_dict
class UnitId(enum):
    archer_line = -299
    cavalry_archer_line = -298
    skirmisher_line = -297
    militiaman_line = -296
    spearman_line = -295
    demolition_ship_line = -294
    fire_ship_line = -293
    galley_line = -292
    battering_ram_line = -291
    mangonel_line = -290
    scorpion_line = -289
    camel_line = -288
    knight_line = -287
    scout_cavalry_line = -286
    cannon_galleon_line = -284
    longboat_line = -283
    turtle_ship_line = -282
    berserk_line = -281
    cataphract_line = -280
    chu_ko_nu_line = -279
    huskarl_line = -278
    janissary_line = -277
    longbowman_line = -276
    mameluke_line = -275
    mangudai_line = -274
    samurai_line = -273
    teutonic_knight_line = -272
    throwing_axeman_line = -271
    war_elephant_line = -270
    war_wagon_line = -269
    woad_raider_line = -268
    jaguar_man_line = -267
    eagle_warrior_line = -266
    plumed_archer_line = -265
    tarkan_line = -264
    conquistador_line = -263
    camel_archer_line = -285
    genoese_crossbowman_line = -262
    elephant_archer_line = -261
    boyar_line = -260
    magyar_huszar_line = -259
    kamayuk_line = -258
    caravel_line = -257
    organ_gun_line = -256
    gbeto_line = -255
    shotel_warrior_line = -254
    genitour_line = -253
    ballista_elephant_line = -252
    rattan_archer_line = -251
    arambai_line = -250
    battle_elephant_line = -249
    karambit_warrior_line = -248
    konnik_line = -247
    krepost_konnik_line = -246
    foot_konnik_line = -245
    leitis_line = -244
    kipchak_line = -243
    keshik_line = -242
    steppe_lancer_line = -241
    coustillier_line = -240
    serjeant_line = -239
    donjon_serjeant_line = -238
    obuch_line = -237
    hussite_wagon_line = -236
    bombard_cannon_line = -235
    urumi_swordsman_line = -234
    ratha_melee_line = -233
    chakram_thrower_line = -232
    armored_elephant_line = -231
    ghulam_line = -230
    shrivamsha_rider_line = -229
    ratha_ranged_line = -228
    donjon_spearman_line = -227
    centurion_line = -226
    composite_bowman_line = -225
    monaspa_line = -224
    qizilbash_warrior_line = -223
    immortal_line = -222
    strategos_line = -221
    hippeus_line = -220
    hoplite_line = -219
    war_chariot_line = -218
    lembos_line = -217
    monoreme_line = -216
    ancient_galley_line = -215
    incendiary_ship_line = -214
    catapult_ship_line = -213
class Value(enum):
    pass #empty options_dict
class VictoryCondition(enum):
    standard = 0
    conquest = 1
    time_limit = 2
    score = 3
    custom = 4
class VictoryPlayer(enum):
    pass #empty options_dict
class VictoryTime(enum):
    pass #empty options_dict
class VictoryType(enum):
    pass #empty options_dict
class WallId(enum):
    stone_wall_line = -399