string_variable_asign = """(defrule   (true)
=>  (up-modify-goal 1 c:= 3)
  (up-modify-goal 1 c:+ 1)
)
"""
string_while_loop = """(defrule   (true)
=>  (up-modify-goal 1 c:= 1)
)
(defrule   (goal 1 0)
=>  (up-jump-rule 1)
)
(defrule   (true)
=>  (up-jump-direct c: 5)
)
(defrule   (true)
=>  (do-nothing)
)
(defrule   (true)
=>  (up-jump-direct c: 1)
)
(defrule   (true)
=>  (do-nothing)
)
"""
string_if = """(defrule   (True)
=>  (up-jump-rule 1)
)
(defrule   (true)
=>  (up-jump-direct c: 3)
)
(defrule   (true)
=>  (do-nothing)
)
(defrule   (true)
=>  (do-nothing)
)
"""
string_nested_if = """(defrule   (true)
=>  (up-modify-goal 1 c:= 1)
)
(defrule   (true)
=>  (up-modify-goal 2 c:= 1)
)
(defrule   (goal 1 0)
=>  (up-jump-rule 1)
)
(defrule   (true)
=>  (up-jump-direct c: 8)
)
(defrule   (goal 2 0)
=>  (up-jump-rule 1)
)
(defrule   (true)
=>  (up-jump-direct c: 7)
)
(defrule   (true)
=>  (do-nothing)
)
(defrule   (true)
=>  (do-nothing)
)
(defrule   (true)
=>  (do-nothing)
)
"""
string_incroment = """(defrule   (true)
=>  (up-modify-goal 1 c:= 0)
)
(defrule   (true)
=>  (up-modify-goal 1 g:= 1)
  (up-modify-goal 1 c:+ 12)
)
(defrule   (true)
=>  (up-modify-goal 1 g:= 1)
  (up-modify-goal 1 c:- 8)
)
"""